export const catalog = Object.freeze([
  {
    id: 'demo-monitor-27',
    manufacturer: 'Northstar Labs',
    name: 'Northstar View 27 QHD Monitor',
    partNumber: 'NSV-27-QHD',
    category: 'Displays',
    availability: 'In stock',
    displayPriceRub: 32900,
  },
  {
    id: 'demo-keyboard-01',
    manufacturer: 'Vector Works',
    name: 'Vector Type Wireless Keyboard',
    partNumber: 'VWK-104-RU',
    category: 'Peripherals',
    availability: 'In stock',
    displayPriceRub: 6490,
  },
  {
    id: 'demo-dock-usbc',
    manufacturer: 'Harbor Systems',
    name: 'Harbor USB-C Office Dock',
    partNumber: 'HBR-DOCK-12',
    category: 'Accessories',
    availability: 'Ships in 3 days',
    displayPriceRub: 18900,
  },
  {
    id: 'demo-headset-pro',
    manufacturer: 'Clearwave',
    name: 'Clearwave Meeting Headset',
    partNumber: 'CW-HS-220',
    category: 'Communications',
    availability: 'In stock',
    displayPriceRub: 11750,
  },
  {
    id: 'demo-router-ax',
    manufacturer: 'Summit Network',
    name: 'Summit Office AX Router',
    partNumber: 'SMT-AX-8',
    category: 'Networking',
    availability: 'Ships in 5 days',
    displayPriceRub: 24400,
  },
  {
    id: 'demo-storage-2tb',
    manufacturer: 'Atlas Storage',
    name: 'Atlas Portable SSD 2 TB',
    partNumber: 'ATL-PSSD-2T',
    category: 'Storage',
    availability: 'Limited stock',
    displayPriceRub: 20900,
  },
]);
